branches:
  only:
  - master
  - feat/*

language: cpp

dist: xenial
os: linux

jobs:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-9
        - g++-9
        - cmake

    before_script:
    - export CC=gcc-9
    - export CXX=g++-9
    - gcc -v && g++ -v && cmake --version

    script: ./make.sh
