branches:
  only:
  - master
  - /^feat\/.+$/

language: cpp

python:
  - 3.7

dist: xenial
os: linux

jobs:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-9
        - g++-9
        - cmake
        - gcovr

    install:
    # Install version 3.16 cmake
    - export DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - export CMAKE_URL="https://www.cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz"
    - mkdir -p ${DEPS_DIR}/cmake
    - travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    # Install conan
    - pip install --user conan
    # Automatic detection of your arch, compiler, etc.
    - conan user
    - conan profile list
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    before_script:
    - export CC=gcc-9
    - export CXX=g++-9
    - gcc -v && g++ -v && cmake --version

    script:
    # Check if the application build successfully
    - ./make.sh
    # Build and run the test
    - ./make.sh Test

    after_success:
      - bash <(curl -s https://codecov.io/bash)
