branches:
  only:
  - master
  - /^feat\/.+$/

language: cpp

python:
  - 3.7

dist: xenial
os: linux

jobs:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - cmake

    install:
    # Install version 3.16 cmake
    - export DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - export CMAKE_URL="https://www.cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz"
    - mkdir -p ${DEPS_DIR}/cmake
    - travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    # Install conan
    - pip install --user conan
    # Automatic detection of your arch, compiler, etc.
    - conan user
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    before_script:
    - export CC=gcc-7
    - export CXX=g++-7
    - gcc -v && g++ -v && cmake --version

    script: ./make.sh
